# Please consult our docs for more info: https://www.librechat.ai/docs/configuration/docker_override

services:
  api:
    volumes:
    - type: bind
      source: ./librechat.yml
      target: /app/librechat.yaml
